---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kustomize-mutating-webhook
  namespace: flux-system
spec:
  secretName: kustomize-mutating-webhook-tls
  dnsNames:
  - kustomize-mutating-webhook.flux-system.svc
  issuerRef:
    name: selfsigned-issuer
