{{- if .Values.certManager.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kustomize-mutating-webhook.fullname" . }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "kustomize-mutating-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kustomize-mutating-webhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.certManager.issuerName }}
    kind: {{ .Values.certManager.issuerKind }}
  secretName: {{ include "kustomize-mutating-webhook.fullname" . }}-tls
  duration: {{ .Values.certManager.certificateDuration | default "1h" }}
  renewBefore: {{ .Values.certManager.certificateRenewBefore | default "30m" }}
{{- end }}
