{{- range $configMap := .Values.configMaps }}
{{- if $configMap.create -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMap.name }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
data:
  {{- toYaml $configMap.data | nindent 2 }}
{{- end }}
{{- end }}
