---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kustomize-mutating-webhook.fullname" . }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kustomize-mutating-webhook.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "kustomize-mutating-webhook.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "kustomize-mutating-webhook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: https
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            {{- range $configMap := .Values.configMaps }}
            - name: {{ $configMap.name }}
              mountPath: /etc/config/{{ regexReplaceAll "\\W+" $configMap.name "_" }}
              readOnly: true
            {{- end }}
            {{- range $secret := .Values.secrets }}
            - name: {{ $secret.name }}
              mountPath: /etc/config/{{ regexReplaceAll "\\W+" $secret.name "_" }}
              readOnly: true
            {{- end }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "kustomize-mutating-webhook.fullname" . }}-tls
        {{- range $configMap := .Values.configMaps }}
        - name: {{ $configMap.name }}
          configMap:
            name: {{ $configMap.name }}
            optional: {{ $configMap.optional | default false }}
        {{- end }}
        {{- range $secret := .Values.secrets }}
        - name: {{ $secret.name }}
          secret:
            secretName: {{ $secret.name }}
            optional: {{ $secret.optional | default false }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
