{{- if .Values.networkpolicy.create -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kustomize-mutating-webhook
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kustomize-mutating-webhook.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow Kubernetes API server to connect with port 8443
    - from:
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress:
    # Allow Webhook server to connect with Kubernetes API server on port 443
    - ports:
      - port: 443
        protocol: TCP
      to:
      - ipBlock:
          cidr: 0.0.0.0/0
{{- end }}
