{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kustomize-mutating-webhook.serviceAccountName" . }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
